# Generated by Django 5.2.17 on 2026-09-08 19:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incursionstatus", "0004_incursion_region_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "region_name",
                    models.CharField(
                        blank=True,
                        help_text="Exact region name (case-insensitive). Leave empty for all regions.",
                        max_length=100,
                    ),
                ),
                ("channel_id", models.CharField(max_length=20)),
                (
                    "role_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional Discord role ID to ping.",
                        max_length=20,
                    ),
                ),
                ("notify_spawn", models.BooleanField(default=True)),
                ("notify_disappearance", models.BooleanField(default=True)),
                (
                    "notify_state",
                    models.BooleanField(
                        default=False, verbose_name="Notify phase changes"
                    ),
                ),
                (
                    "notify_boss",
                    models.BooleanField(
                        default=False, verbose_name="Notify boss availability changes"
                    ),
                ),
                (
                    "notify_influence",
                    models.BooleanField(
                        default=False, help_text="May send an alert every ESI update."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incursionstatus.incursionchange",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incursionstatus.notificationrule",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rule", "change"),
                        name="incursion_notification_rule_change",
                    )
                ],
            },
        ),
    ]
