# Generated by Django 5.2.17 on 2026-09-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incursionstatus", "0005_notificationrule_notificationdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrule",
            name="ping_everyone",
            field=models.BooleanField(
                default=False,
                help_text="Ping @everyone instead of the role ID when enabled.",
            ),
        ),
    ]
