# Generated by Django 5.2.17 on 2026-09-08 19:54

from django.db import migrations, models


def backfill_phase_times(apps, schema_editor):
    Incursion = apps.get_model("incursionstatus", "Incursion")
    Change = apps.get_model("incursionstatus", "IncursionChange")
    alias = schema_editor.connection.alias
    for incursion in Incursion.objects.using(alias).all().iterator():
        changes = Change.objects.using(alias).filter(
            incursion_id=incursion.pk, observed_at__gte=incursion.first_seen,
        ).order_by("-observed_at", "-pk")
        for change in changes.iterator():
            if change.change_type == "appeared" or (
                change.change_type == "updated" and "state" in change.changed_fields
            ):
                if change.snapshot.get("state") == incursion.state:
                    Incursion.objects.using(alias).filter(pk=incursion.pk).update(
                        last_state_change=change.observed_at,
                    )
                break


class Migration(migrations.Migration):

    dependencies = [
        ("incursionstatus", "0006_notificationrule_ping_everyone"),
    ]

    operations = [
        migrations.AddField(
            model_name="incursion",
            name="last_state_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_phase_times, migrations.RunPython.noop),
        migrations.AddField(
            model_name="notificationdelivery",
            name="embed",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
