# Generated by Django 5.2.17 on 2026-09-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incursionstatus", "0007_incursion_last_state_change_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incursionsyncstatus",
            name="consecutive_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="incursionsyncstatus",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
